```{r}
library(tidyverse)
```
```{r}
data <- read_delim("data/data_csv.csv", delim = ",", n_max = 10)
data
```

```{r}
data <- read_delim("data/data_csv.csv", delim = ",", n_max = 10)

data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$'Группа крови' <- factor(data$'Группа крови')
data
```
```{r}
write_delim(data, "out/data_csv.csv", delim =',')
list.files("out")
```

```{r}
data <- read_csv2("data/data_csv2.csv", skip =0, n_max = 10)
data
```

```{r}
write_excel_csv(data, "out/data_csv.csv")
```
```{r}
write_excel_csv2(data, "out/data_csv2.csv")
```
```{r}
write_tsv(data, "out/data_tsv.tsv")
```

```{r}
read_tsv("data/data_tsv.tsv", skip = 0, n_max = 1000)
```
```{r}
readxl::read_excel("data/data_excel.xlsx", sheet = "data")
```
```{r}
openxlsx::write.xlsx(data, "out/data_excel.xlsx", colNames = TRUE)
```
```{r}
openxlsx::write.xlsx(data,"data/data_csv2.xlsx", colNames = TRUE)
```
```{r}
readxl::read_excel("data/data_csv2.xlsx")
```
```{r}
read_rds("data/data_rds.rds")

write_rds(data, "out/data_rds.rds")
```

```{r}
data
```

```{r}
data$ 'Группа крови'
```
```{r}
data [["Группа крови"]]
```
```{r}
tibble ( 
     var_first = 1:10,
     var_second = var_first^2
)
```
```{r}
tibble (
     var_first = 1:10,
     var_second = if_else(var_first < 5, var_first + 100, var_first)
)
```

```{r}
data
```
```{r}
data |> select('Группа', function(x) !is.factor(x))
```
```{r}
data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), function(x) mean(x, na.rm = TRUE)))

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
```
```{r}
library(tidyverse)
library(flextable)
```
```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)
statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)
table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
table |> 
  flextable()
```
```{r}
table |> 
  flextable() |> 
  theme_alafoli()
```
```{r}
table <- tibble(
  `Adverse events` = c(
    "SOC Желудочно-кишечные кровотечения",
    "PT Тошнота",
    "SOC Нарушения со стороны нервной системы",
    "PT Головная боль"
  )
)

table |> 
  flextable() |> 
  theme_box() |> 
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |> 
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |> 
  bold(i = ~ str_detect(`Adverse events`, "SOC")) |> 
  italic(i = ~ str_detect(`Adverse events`, "PT")) |> 
  width(width = 15)
```

```{r}
is_pvalue_sign <- function(x) {
  as.numeric(str_remove(x, "<")) <= 0.05
}

tibble("p-value" = c("0.01", "0.38", "0.124", "0.005", "0.05")) |> 
  flextable() |> 
  theme_box() |> 
  bg(i = ~ is_pvalue_sign(`p-value`), bg = "orange")
```